### PR TITLE
Uppercase issue solved

### PR DESCRIPTION
**Pull request by cnonnet**
Here is my pull request related to the uppercase issue when a user is added or updated in the database

### CODE REVIEW

**Comment by rbaltrusch** [comment]
Hi @cnonnet , thanks for submitting your pull request!

The changes look good and seem to fix the issue.

I have a few review comments to give before merging:

- Have you considered the in-built string method ```str.title()```? It is a robust way to solve the problem and would get around the string splicing.
- To get around indexing ```user_data```, it would be a bit more readable to use tuple unpacking: ```first_name, last_name, *rest = user_data```
- Do we also need the fix in ```callbacks.edit_user_data```? If possible, I would like to keep the data cleansing in one place (best would be the database and its interface, database.py), this way we encapsulate the complexity.

In my opinion, the current implementation is not DRY (don't repeat yourself) enough at the moment. I think it would be helpful to write a small helper function to avoid the repetition. This helper function could either reside directly in database.py or maybe in the user.py file (maybe directly as part of the ```UserData``` class (that might be the cleanest solution -> implement ```UserData.first_name``` and ```UserData.last_name``` as a [property](https://www.programiz.com/python-programming/property), with the getter returning the uppercased string).

Thanks again for the PR, I'll accept it as soon as we clear up the review points :) Let me know if there are any difficulties.

Best, Richard

**Review by rbaltrusch — CHANGES_REQUESTED** [review]
- Have you considered the in-built string method ```str.title()```? It is a robust way to solve the problem and would get around the string splicing.
- To get around indexing ```user_data```, it would be a bit more readable to use tuple unpacking: ```first_name, last_name, *rest = user_data```
- Do we also need the fix in ```callbacks.edit_user_data```? If possible, I would like to keep the data cleansing in one place (best would be the database and its interface, database.py), this way we encapsulate the complexity.

In my opinion, the current implementation is not DRY (don't repeat yourself) enough at the moment. I think it would be helpful to write a small helper function to avoid the repetition. This helper function could either reside directly in database.py or maybe in the user.py file (maybe directly as part of the ```UserData``` class (that might be the cleanest solution -> implement ```UserData.first_name``` and ```UserData.last_name``` as a [property](https://www.programiz.com/python-programming/property), with the getter returning the uppercased string).

**Comment by cnonnet** [comment]
Hi @rbaltrusch, thanks for your review,

I followed your proposition and changed my approach, I modified directly the user.py so that every UserData is created with an uppercase first_name and last_name. I used ths title() method as you requested, it is indeed much more readable.
No changed were needed in database.py since UserData has the correct format.
However, I did not use a property as you suggested because I think that what I implemented is enough, feel free to tell me if want me to use a property and a getter or if that is ok as it is.
Sorry for the delay, I am working on a lot on others things these days.

Best, Clément

**Review by rbaltrusch — APPROVED** [review]
Looks good, changes are much more modular now 👍

**Comment by rbaltrusch** [comment]
Hi @cnonnet , I merged the PR now, thanks for your contribution :-)

**Pull request merged**
